-- MySQL Script generated by MySQL Workbench
-- Mon Aug 12 10:47:21 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Hotel_Management_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Hotel_Management_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Hotel_Management_db` DEFAULT CHARACTER SET utf8 ;
USE `Hotel_Management_db` ;

-- -----------------------------------------------------
-- Table `Hotel_Management_db`.`Hotelchain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hotel_Management_db`.`Hotelchain` (
  `Hotelchain_Id` INT NOT NULL,
  `City` VARCHAR(45) NULL,
  `Country` VARCHAR(45) NULL,
  `Name` VARCHAR(45) NULL,
  `Rank` INT NULL,
  `Year_Established` INT NULL,
  PRIMARY KEY (`Hotelchain_Id`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE,
  UNIQUE INDEX `Year_Established_UNIQUE` (`Year_Established` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel_Management_db`.`Hotels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hotel_Management_db`.`Hotels` (
  `Hotels_id` INT NOT NULL,
  `Hotel_name` VARCHAR(45) NOT NULL,
  `Hotel_Description` VARCHAR(45) NULL,
  `Ratings` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `Url` VARCHAR(45) NULL,
  `Hotel_Chain_ID` INT NOT NULL,
  `Rating_Image` BLOB NULL,
  `Country` VARCHAR(45) NULL,
  PRIMARY KEY (`Hotels_id`),
  UNIQUE INDEX `Address_UNIQUE` (`Address` ASC) VISIBLE,
  INDEX `Hotelchain_ID_idx` (`Hotel_Chain_ID` ASC) VISIBLE,
  CONSTRAINT `Hotelchain_ID`
    FOREIGN KEY (`Hotel_Chain_ID`)
    REFERENCES `Hotel_Management_db`.`Hotelchain` (`Hotelchain_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel_Management_db`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hotel_Management_db`.`Customers` (
  `Customers_id` INT NOT NULL,
  `Customer_name` VARCHAR(45) NOT NULL,
  `Adrdess` VARCHAR(45) NULL,
  `Age` INT NULL,
  PRIMARY KEY (`Customers_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel_Management_db`.`Sevices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hotel_Management_db`.`Sevices` (
  `Services_id` INT NOT NULL,
  `Services` VARCHAR(45) NOT NULL,
  `Hotels_Hotels_id` INT NOT NULL,
  PRIMARY KEY (`Services_id`),
  INDEX `fk_Sevices_Hotels1_idx` (`Hotels_Hotels_id` ASC) VISIBLE,
  CONSTRAINT `fk_Sevices_Hotels1`
    FOREIGN KEY (`Hotels_Hotels_id`)
    REFERENCES `Hotel_Management_db`.`Hotels` (`Hotels_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel_Management_db`.`Hotel_Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hotel_Management_db`.`Hotel_Staff` (
  `Staff_id` INT NOT NULL,
  `Staff_name` VARCHAR(45) NOT NULL,
  `Staff_Age` VARCHAR(45) NULL,
  `Work_in_department` VARCHAR(45) NULL,
  `Salary` INT NULL,
  `Hotels_Hotels_id` INT NOT NULL,
  `Sevices_Services_id` INT NOT NULL,
  PRIMARY KEY (`Staff_id`),
  INDEX `fk_Hotel_Staff_Hotels1_idx` (`Hotels_Hotels_id` ASC) VISIBLE,
  INDEX `fk_Hotel_Staff_Sevices1_idx` (`Sevices_Services_id` ASC) VISIBLE,
  CONSTRAINT `fk_Hotel_Staff_Hotels1`
    FOREIGN KEY (`Hotels_Hotels_id`)
    REFERENCES `Hotel_Management_db`.`Hotels` (`Hotels_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hotel_Staff_Sevices1`
    FOREIGN KEY (`Sevices_Services_id`)
    REFERENCES `Hotel_Management_db`.`Sevices` (`Services_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel_Management_db`.`Room_Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hotel_Management_db`.`Room_Type` (
  `Type_id` INT NOT NULL,
  `Type_name` VARCHAR(45) NULL,
  PRIMARY KEY (`Type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel_Management_db`.`Rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hotel_Management_db`.`Rooms` (
  `Room_id` INT NOT NULL,
  `Room_no` INT NOT NULL,
  `Services` VARCHAR(45) NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  `Smooking` VARCHAR(45) NOT NULL,
  `Room_Avaliable` VARCHAR(45) NOT NULL,
  `Price` INT NOT NULL,
  `Date_of_available` DATE NULL,
  `Jan_March_discount` INT NULL,
  `July_August_Discount` INT NULL,
  `Sep_Dec_Discount` INT NULL,
  `Room_Description` VARCHAR(45) NULL,
  `Hotels_Hotels_id` INT NOT NULL,
  `Room_Type_Type_id` INT NOT NULL,
  PRIMARY KEY (`Room_id`),
  INDEX `fk_Rooms_Hotels1_idx` (`Hotels_Hotels_id` ASC) VISIBLE,
  UNIQUE INDEX `Room_no_UNIQUE` (`Room_no` ASC) VISIBLE,
  INDEX `fk_Rooms_Room_Type1_idx` (`Room_Type_Type_id` ASC) VISIBLE,
  CONSTRAINT `fk_Rooms_Hotels1`
    FOREIGN KEY (`Hotels_Hotels_id`)
    REFERENCES `Hotel_Management_db`.`Hotels` (`Hotels_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rooms_Room_Type1`
    FOREIGN KEY (`Room_Type_Type_id`)
    REFERENCES `Hotel_Management_db`.`Room_Type` (`Type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel_Management_db`.`Bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hotel_Management_db`.`Bookings` (
  `Booking_id` INT NOT NULL,
  `Customers_Customers_id` INT NOT NULL,
  `Hotels_Hotels_id` INT NOT NULL,
  `Check_in_Date` DATETIME NOT NULL,
  `Check_out_Date` DATETIME NULL,
  `Rooms_Room_id` INT NOT NULL,
  `Methiod_of_payment` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Booking_id`),
  INDEX `fk_Bookings_Customers1_idx` (`Customers_Customers_id` ASC) VISIBLE,
  INDEX `fk_Bookings_Hotels1_idx` (`Hotels_Hotels_id` ASC) VISIBLE,
  INDEX `fk_Bookings_Rooms1_idx` (`Rooms_Room_id` ASC) VISIBLE,
  CONSTRAINT `fk_Bookings_Customers1`
    FOREIGN KEY (`Customers_Customers_id`)
    REFERENCES `Hotel_Management_db`.`Customers` (`Customers_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bookings_Hotels1`
    FOREIGN KEY (`Hotels_Hotels_id`)
    REFERENCES `Hotel_Management_db`.`Hotels` (`Hotels_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bookings_Rooms1`
    FOREIGN KEY (`Rooms_Room_id`)
    REFERENCES `Hotel_Management_db`.`Rooms` (`Room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel_Management_db`.`Floors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hotel_Management_db`.`Floors` (
  `Floor_id` INT NOT NULL,
  `Level_of_Foors` INT NOT NULL,
  `Rooms_Room_id` INT NOT NULL,
  `Hotels_Hotels_id` INT NOT NULL,
  PRIMARY KEY (`Floor_id`),
  INDEX `fk_Floors_Rooms1_idx` (`Rooms_Room_id` ASC) VISIBLE,
  INDEX `fk_Floors_Hotels1_idx` (`Hotels_Hotels_id` ASC) VISIBLE,
  CONSTRAINT `fk_Floors_Rooms1`
    FOREIGN KEY (`Rooms_Room_id`)
    REFERENCES `Hotel_Management_db`.`Rooms` (`Room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Floors_Hotels1`
    FOREIGN KEY (`Hotels_Hotels_id`)
    REFERENCES `Hotel_Management_db`.`Hotels` (`Hotels_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel_Management_db`.`Room_sevices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hotel_Management_db`.`Room_sevices` (
  `idRoom_sevices` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  PRIMARY KEY (`idRoom_sevices`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel_Management_db`.`Rooms_has_Room_sevices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hotel_Management_db`.`Rooms_has_Room_sevices` (
  `Rooms_Room_id` INT NOT NULL,
  `Room_sevices_idRoom_sevices` INT NOT NULL,
  PRIMARY KEY (`Rooms_Room_id`, `Room_sevices_idRoom_sevices`),
  INDEX `fk_Rooms_has_Room_sevices_Room_sevices1_idx` (`Room_sevices_idRoom_sevices` ASC) VISIBLE,
  INDEX `fk_Rooms_has_Room_sevices_Rooms1_idx` (`Rooms_Room_id` ASC) VISIBLE,
  CONSTRAINT `fk_Rooms_has_Room_sevices_Rooms1`
    FOREIGN KEY (`Rooms_Room_id`)
    REFERENCES `Hotel_Management_db`.`Rooms` (`Room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rooms_has_Room_sevices_Room_sevices1`
    FOREIGN KEY (`Room_sevices_idRoom_sevices`)
    REFERENCES `Hotel_Management_db`.`Room_sevices` (`idRoom_sevices`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
